### PR TITLE
Added support to Sponge Configuration Yaml

### PR DESCRIPTION
**Pull request by alexissdev**

### CODE REVIEW

**Comment by OcZi** [comment]
If Sponge uses Configurate maybe the implementation can be generic to support all the codecs (XML, YAML, JSON, etc)?
Only if it is not difficulty or impossible to do.

**Comment by alexissdev** [comment]
the module says specifies that it is sponge-yaml, supporting only yaml as specified

**Comment by OcZi** [comment]
> the module says specifies that it is sponge-yaml, supporting only yaml as specified

Configurate has a abstract layer to work with (A.K.A Core).
I think the configuration loader could be passed as a parameter to support all formats.
Maybe I'm wrong, I don't have experience with Configurate.

**Comment by alexissdev** [comment]
As far as I know, the use between modules is separated to use them individually, how does nmessage work?

**Comment by OcZi** [comment]
> As far as I know, the use between modules is separated to use them individually, how does nmessage work?

Actually it is.
Having support to configurate can be an advantage for any sponge dev to use nmessage.
In any case, it would be yusshu's decision.

**Comment by yusshu** [comment]
I agree with @OcZi, and why did you move `sourcetype-properties` test (re)sources?

**Comment by alexissdev** [comment]
what?, it could be that I have moved it without realizing it sorry

**Pull request closed without merging**
